### ISSUE TITLE
Feature milestone

### ISSUE THREAD

**Issue by EvadeMaster** [EvadeMaster/revanced-manager#14]
### Type

Functionality

### Issue

a

### Feature

a

### Motivation

a

### Additional context

a

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager
